[package]
name = "rebirth_crate"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { version = "0.2.0", features = [
    "register-docs",
    "experimental-threads",
    "api-4-3",
    "serde",
] }
ron = "0.8.1"
serde = "1.0.215"
